// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupExperimentPrefs.network.cookie.cookieBehavior", 0);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "b107f21b-38c8-47df-8f96-02ac27a35f35");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1551923780);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1551923900);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1551923300);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1551923540);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1551923420);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1551923660);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1551837252);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1551924020);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1024000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1551836382);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"34782\":1551923276977,\"34827\":1551836392462,\"34838\":1551836392462,\"34840\":1551923276977}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{76423f75-a1b3-4d8b-8f6d-10116fe3a181}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1551848400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1551923283299");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1551925089299");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1551923283563");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1551926883563");
user_pref("browser.search.region", "CA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001155");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1551923278");
user_pref("browser.slowStartup.averageTime", 10743);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215001155");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1551836390781");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "1e360a3393d8442ebaf02c7f947593fa");
user_pref("extensions.blocklist.lastModified", "Tue, 05 Mar 2019 14:09:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1551923781);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001155");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{dcbf1379-53de-495e-9a37-720b04ecd4eb}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"},\"webcompat@mozilla.org\":{\"version\":\"3.0.1\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"5c15b603-0ac7-4aab-a924-1ad49d782f2e\",\"screenshots@mozilla.org\":\"9f8c49a7-197a-427a-8a52-04b6c494ed17\",\"webcompat-reporter@mozilla.org\":\"3900040b-e5a9-4bef-a409-75322e3e3f25\",\"webcompat@mozilla.org\":\"7497aa91-e3c9-4503-8fe6-1e228b6dae86\",\"fxmonitor@mozilla.org\":\"1fd05f50-f231-43d8-8564-0c6ec93cf35c\"}");
user_pref("idle.lastDailyNotification", 1551837690);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 37);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1551836485);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190215001155");
user_pref("media.gmp-manager.lastCheck", 1551923563);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1551837691);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "c2d0cf58-8d5c-42e1-91ba-298b6e5fb6ca");
user_pref("security.sandbox.plugin.tempDirSuffix", "3f84c249-7a33-4344-804d-2462147ccda4");
user_pref("services.blocklist.addons.checked", 1551923791);
user_pref("services.blocklist.gfx.checked", 1551923791);
user_pref("services.blocklist.onecrl.checked", 1551923791);
user_pref("services.blocklist.pinning.checked", 1551923791);
user_pref("services.blocklist.plugins.checked", 1551923791);
user_pref("services.settings.clock_skew_seconds", -131);
user_pref("services.settings.last_update_seconds", 1551923791);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1551923791);
user_pref("services.settings.main.language-dictionaries.last_check", 1551923791);
user_pref("services.settings.main.onboarding.last_check", 1551923791);
user_pref("services.settings.main.sites-classification.last_check", 1551923791);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1551837691);
user_pref("toolkit.startup.last_success", 1551923265);
user_pref("toolkit.telemetry.cachedClientID", "5720f389-e19d-46cf-9e34-55bea6986ec5");
user_pref("toolkit.telemetry.previousBuildID", "20190215001155");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
